dev:
  ALLOWED_HOSTS:
    - '*'
  DEBUG: True
  Q_CLUSTER:
    name: DjangORM
    workers: 4
    timeout: 90
    retry: 120
    queue_limit: 50
    bulk: 10
    orm: default
    catch_up: False
    sync: True
production:
  ALLOWED_HOSTS:
    - 'mergify.net'
  DEBUG: False
  Q_CLUSTER:
    name: DjangORM
    workers: 4
    timeout: 90
    retry: 120
    queue_limit: 50
    bulk: 10
    orm: default
    catch_up: False