# Generated by Django 4.0.5 on 2022-06-25 21:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socialaccount', '0003_extra_data_default_dict'),
    ]

    operations = [
        migrations.CreateModel(
            name='BasePlaylist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=96, null=True)),
                ('name', models.CharField(default='', max_length=512)),
                ('size', models.IntegerField(default=0)),
                ('snapshot_id', models.CharField(max_length=128, null=True)),
                ('spotify_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='socialaccount.socialaccount')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentPlaylist',
            fields=[
                ('baseplaylist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='back.baseplaylist')),
                ('allow_duplicates', models.BooleanField(default=False)),
            ],
            bases=('back.baseplaylist',),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uri', models.CharField(max_length=96, null=True)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.baseplaylist')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('baseplaylist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='back.baseplaylist')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back.parentplaylist')),
            ],
            bases=('back.baseplaylist',),
        ),
    ]
