# Generated by Django 4.0.5 on 2022-06-27 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0002_alter_baseplaylist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseplaylist',
            name='name',
            field=models.CharField(default='Merged Playlist', max_length=512, null=True),
        ),
    ]
